"""Added table

Revision ID: 9212aca8f813
Revises: 
Create Date: 2023-06-22 18:02:27.766860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9212aca8f813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=128), nullable=False),
    sa.Column('open_time', sa.String(length=128), nullable=False),
    sa.Column('open', sa.String(length=255), nullable=False),
    sa.Column('high', sa.String(length=255), nullable=False),
    sa.Column('low', sa.String(length=255), nullable=False),
    sa.Column('close', sa.String(length=255), nullable=False),
    sa.Column('volume', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('data', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_data')
    op.drop_table('binance_data')
    # ### end Alembic commands ###
